### ISSUE TITLE
RuntimeWarning: Mean of empty slice

### ISSUE THREAD

**Issue by NabilaRahman** [ay-lab/ExTraMapper#1]
Hi, I'm trying to get transcript orthologs for mouse and human. 

1. I generated wiggle files using PhastCon on MAF files pregenerated by ensembl e,g (http://hgdownload.cse.ucsc.edu/goldenPath/mm10/vsHg38/mafSynNet/). 
2. Ran the preprocess step 0 and 1. 
3. Fixed the columns for the ensembl homolog files to match parse_ensembl_geneAndProtein_pairings input. 

But at the "extract_conservation_stats_for_exons" stage I get

> /media/Linux/Packages/ExTraMapper-master/scripts/ensemblUtils.py:1083: RuntimeWarning: Mean of empty slice
>   preAcceptorCons=np.nanmean(x)
> /media/Linux/Packages/ExTraMapper-master/scripts/ensemblUtils.py:1089: RuntimeWarning: Mean of empty slice
>   exon5primeCons=np.nanmean(x)
> /media/Linux/Packages/ExTraMapper-master/scripts/ensemblUtils.py:1092: RuntimeWarning: Mean of empty slice
>   exonMidCons=np.nanmean(x)
> /media/Linux/Packages/ExTraMapper-master/scripts/ensemblUtils.py:1095: RuntimeWarning: Mean of empty slice
>   exon3primeCons=np.nanmean(x)
> /media/Linux/Packages/ExTraMapper-master/scripts/ensemblUtils.py:1101: RuntimeWarning: Mean of empty slice
>   postDonorCons=np.nanmean(x)
> /media/Linux/Packages/ExTraMapper-master/scripts/ensemblUtils.py:1109: RuntimeWarning: Mean of empty slice
>   exonDic[id].avgConsScore=np.nanmean(allScores[fivePrimeFlank:-threePrimeFlank])
> 0       /media/Linux/Packages/ExTraMapper-master/scripts/ensemblUtils.py:1111: RuntimeWarning: Mean of empty slice
>   exonDic[id].avgCodingConsScore=np.nanmean(codingScores)

Is this something wrong with my wiggle files, or something else entirely?

**Comment by ay-lab** [comment]
Hi,
I can try to help you but will require more info. However, we do have the
human-mouse orthologs pre-computed already. Would that be easier if we let
those mappings available on GitHub instead?
Best,

**Comment by NabilaRahman** [comment]
That would be fantastic yes. I am looking for transcript - transcript mapping mainly. What version is this ensembl annotation version is this precomputed data? (for me 91 or up will work)

**Comment by ay-lab** [comment]
Hi,

We have uploaded the transcript mapping file Human-Mouse.Filtered_Transcript_Mapping.xlsx. You can use this file for your use.

We have used the following ensembl versions for mapping

Homo_sapiens.GRCh38.81.gff3
Mus_musculus.GRCm38.81.gff3

**Comment by NabilaRahman** [comment]
Much appreciated. That will do just fine.
