### ISSUE TITLE
Need extra file for running ExTraMapper

### ISSUE THREAD

**Issue by YangpingLi** [ay-lab/ExTraMapper#2]
Hi,

I tried to install the ExTraMapper and all dependent python packages. And run command as the example:

**source config.conf
export EXTRAMAPPER_DIR=$EXTRAMAPPERDIR
MAPPED_EXON_THRES=1.0
genePairId="ENSG00000157764-ENSMUSG00000002413"
python $EXTRAMAPPER_DIR/scripts/ExTraMapper.py $MAPPED_EXON_THRES $org1 $org2 $genePairId > Outputs.txt**

But I encountered an error here:

**Finding exon mappings for gene pair number 0	ENSG00000157764-ENSMUSG00000002413
Traceback (most recent call last):
  File "/projects/compbio/users/byao5/Software/ExTraMapper/scripts/ExTraMapper.py", line 1577, in <module>
    main(sys.argv)
  File "/projects/compbio/users/byao5/Software/ExTraMapper/scripts/ExTraMapper.py", line 1560, in main
    geneDic1,transcriptDic1,exonDic1=pickle.load(open(infilename,"rb"))
IOError: [Errno 2] No such file or directory: '/projects/compbio/users/byao5/Software/ExTraMapper/preprocess/data/human-mouse/perGenePairPickledInfo/ENSG00000157764-ENSMUSG00000002413/org1.pickledDictionaries'**

It seems like I need a file in **perGenePairPickledInfo** but I don't have this directory. How can I fix this issue?

Thanks in advance!

Yangping

**Comment by YangpingLi** [comment]
It seems I haven't run preprocess data. I'll update if it works.

**Comment by YangpingLi** [comment]
I tried to run **runall** in preprocess but it only download **human-mouse, liftover_chains and reference_genomes** in folder **data**. 
Then I tried **runall 1** and encountered an error. It seems I don't have **mafFiles** and apparently I cannot copy it from **/home/ferhatay/NU/shared/ferhat_yingtao** (which is described in the script **runall**).
Could you please explain to me how to run this **preprocess** to prepare data for **ExTraMapper.py**?

Thanks in advance!

Yangping

**Comment by ay-lab** [comment]
Hi, 

Due to the size limitation of github we can't upload the output files of phastCons. But you can definitely generate any species specific phastCons score files by following their usage  http://compgen.cshl.edu/phast/help-pages/phastCons.txt  

And FYI, if you're interested in using human-mouse transcripts, then please use the precalculated "Human-Mouse.Filtered_Transcript_Mapping.xlsx" file or can look at this website https://ay-lab-tools.lji.org/extramapper/index.html
