### ISSUE TITLE
how do I use the script to preprocess the data with my local annotations?

### ISSUE THREAD

**Issue by Yuzhang0102** [ay-lab/ExTraMapper#3]
Hi, 
I want to find exon orthologs from two non-model organisms, and I want to use the annotation made by my lab. So I need to start the preprocess at step2, which folder I need to put the data and the script can find them and continue the script?
Or the script only finish with ensemble annotation?

MAny thanks in advance!
Yu

**Comment by ay-lab** [comment]
Hi Yu,

The step2 is dependent on multiple files generated from step1. 
You can check the 'main()' module in the extramapper python script to the get a sense of required input files. 
I would suggest to run the examples specially human-mouse preprocessing steps and look at the generated input files for details. Let us know how it goes and I will happy to help you out on this.
