### ISSUE TITLE
error when running extMpreprocess at step 3: Undefined subroutine &main::createpicklefiles called at ./extMpreprocess line 694

### ISSUE THREAD

**Issue by majinfa** [ay-lab/ExTraMapper#5]
Hi, 

I want to use ExTraMapper to detect orthologous isoforms between human and chimpanzee, but I can not successfully prepare input files following the directions. 

In fact, I can not run the whole process to prepare input files for human and mouse, just using the examples. It gives an error:  Undefined subroutine &main::createpicklefiles called at ./extMpreprocess line 694. By the way, I have installed genomedata before running extMpreprocess.

Could you please give any suggestions?

Many thanks,
Jinfa Ma

**Comment by ay-lab** [comment]
Hi, 

Are you using python 3 or later version? and have installed 'pickle' library separately?

**Comment by majinfa** [comment]
Hi, 

The python version is 3.8.5 and ''pickle' is already installed, so I do not install 'pickle' separately.

**Comment by ay-lab** [comment]
I would request you to download the extMpreprocess file and give it a try again. I think this is due to the wrong function naming issue. Let me know.
